### ISSUE TITLE
New wallets do not Sync

### ISSUE THREAD

**Issue by JettScythe** [gcash/neutrino#24]
Just cleared my app data & cache since I wanted to generate a new wallet. 
Not quite sure why, but the blockchain height stays at 0 and refuses to sync. I just tried to onboard a friend to this wallet today too - same issue for him. Clicking "Rescan blocks" causes Neutrino to crash. My phone: Android 8.1 
Model ASUS_X018D

**Comment by cpacia** [comment]
Currently waiting for a few more nodes to get synced up. There was a recent change on the full node side and we need people to migrate.

**Comment by JettScythe** [comment]
I have a node set up. Is there anyway that connecting to that could help sync? Also, apologies if this belongs in https://github.com/gcash/android-neutrino instead.

**Comment by JettScythe** [comment]
Connected to my node, blockchain in settings is showing correct height now.

**Comment by cpacia** [comment]
Great!
