### ISSUE TITLE
Swiping "Send" twice results in ghost transaction

### ISSUE THREAD

**Issue by imaginaryusername** [gcash/neutrino#26]
Between the time when "send" button is swiped and when the "successful" animation shows up, it seems possible to swipe "send" again, which results in a weird behavior of pulling in unrelated transactions ("send $0"). In my case this made it into my wallet history: https://www.blockchain.com/bch/tx/c642b114f84753bbf2a75f010f9ef2cc168881ba07e1be579e889f26cf919233

**Comment by cpacia** [comment]
Thanks for the report. Moving issue to here https://github.com/gcash/android-neutrino/issues/23
